[package]
name = "applykit_export"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
